### PR TITLE
Update to SBT 1.5.2 and fix deprecation and other warnings

### PR DESCRIPTION
**Pull request by TorunR**
SBT > 1.5.0 deprecates the "in" Syntax...

### CODE REVIEW

**Comment by TorunR** [comment]
I guess this is blocked until [this issue](https://github.com/scalate/scalate/issues/309) is fixed

**Comment by errt** [comment]
What is the state of this PR now?

**Comment by errt** [comment]
As far as I understand, we can't do this, because for sbt 1.5.2 we would need to go to scalate 1.9.7 which requires scala-parser-combinators 2.0.0 which currently isn't compatible with other dependencies that we have, such as the sbt-pgp plugin, right? Looks like we have to postpone this PR then until this incompatibility is resolved. Not a major issue though to not update sbt right now, is it?

**Comment by TorunR** [comment]
I don't think it is a problem if we postpone this. I initially started this because of Scala 3, which has other blockers anyway

**Comment by errt** [comment]
Any news on this? If possible, I would really like to upgrade to a more recent version of SBT.

**Comment by TorunR** [comment]
The scalate issue is resolved, and the CI and for me locally it worked.

**Review by errt — APPROVED** [review]

**Pull request merged**
